
name: Build Easing Viewer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Geode mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          build-config: Release
          target: Win64

      - name: Upload Geode mod
        uses: actions/upload-artifact@v4
        with:
          name: Easing-Viewer-Build
          path: ${{ steps.build.outputs.build-output }}
          if-no-files-found: error
